# Generated by Django 5.0 on 2024-04-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='erpid',
            new_name='username',
        ),
    ]
