# Generated by Django 4.2.11 on 2024-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_rename_erpid_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='+91', max_length=10),
        ),
    ]
