# Generated by Django 4.2.11 on 2024-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='+91', max_length=13),
        ),
    ]
