# Generated by Django 4.2.11 on 2024-04-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_alter_student_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institute.student')),
                ('topic', models.CharField(max_length=256)),
                ('total_marks', models.IntegerField()),
                ('marks_obtained', models.IntegerField()),
            ],
            bases=('institute.student',),
        ),
    ]
