# Generated by Django 5.0 on 2024-04-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_remove_teacher_class_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='achievements',
            field=models.CharField(default='unknown', max_length=56),
        ),
    ]
