# Generated by Django 4.2.11 on 2024-04-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student_ptr',
        ),
        migrations.AddField(
            model_name='marks',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
