# Generated by Django 4.2.11 on 2024-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_remove_marks_student_ptr_marks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='topic',
            field=models.CharField(default='topic', max_length=256),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
