# Generated by Django 4.2.11 on 2024-04-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_alter_marks_marks_obtained_alter_marks_topic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
